### ISSUE TITLE
Sitemaps: missing default color for valuecolor

### ISSUE THREAD

**Issue by metbril** [openhab/openhab-docs#316] opened 2017-02-10 07:51 UTC
Proposal: add value color 'default' to possible colors.

If using `valuecolor`, one sometimes needs to set default color for default values.

For example:

If you specify
```php
Text item=System_CPU_Load valuecolor=[System_CPU_Load=="NULL"="lightgray",System_CPU_Load>90="red",>40="orange"]
```

then any time the color has changed to orange, it will not revert back to the default color when <= 40. This can be resolved by adding an additional color for any remaining value, like:

```php
Text item=System_CPU_Load valuecolor=[System_CPU_Load=="NULL"="lightgray",System_CPU_Load>90="red",>40="orange",<=40="black"]
```

However, both "black", "gray" and "lightgray" do not match the default color (at least in Basic UI). Perhaps the UI should present the default color (and this is a bug in the UI), or it should be possible to define a mapping like `<=40="default"` in the sitemap.

If `default` is impossible, then the documentation should include the color code to use for default values.

Hacking through the code showed that a class 'grey-700' is used that maps to `#616161`.

https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/web/mdl/material.min.css

**Comment by ThomDietrich** [comment] 2017-02-10 11:26
I'm unsure if this is in need of a documentation solution... To me it sounds like either a bug or a feature request.

>  any time the color has changed to orange, it will not revert back to the default color when <= 40

Are you sure? I have similar elements doing what they are supposed to. In the following example the default state (0) is always presented in "default" color.

```java
Text item=OpState valuecolor=[1="olive", 2="green", 3="maroon"]
```

**Comment by rtvb** [comment] 2017-02-10 13:48
Perhaps you are correct.

I did some more testing. As long as the value stays below the treshold of 40, it has the default color. When it passes the threshold of 40 it becomes orange. But when it then lowers back below the threshold (say 10%) it remains orange and never turns back to the default color.

Should we consider this a bug to be reported to eclipse smarthome repo?

**Comment by ThomDietrich** [comment] 2017-02-10 14:11
Yes I think you can do that right away. However I believe you need to do some more testing because with my discrete values example shown above, I do not encounter that bug.

**Comment by ThomDietrich** [comment] 2017-02-19 20:26
Any update? Did you report a bug? Is there still an issue related to documentation?

**Comment by rtvb** [comment] 2017-02-20 06:02
No I did not have the time yet.

**Comment by rtvb** [comment] 2017-03-16 21:07
@ThomDietrich Issue https://github.com/eclipse/smarthome/issues/3065 is closed. The bug should be fixed. Should we close this issue too or add it to #53?

**Comment by ThomDietrich** [comment] 2017-03-17 14:21
Depends... if the issue is fixed (great) what's still needed in docs?

**Closed** 2017-09-03 13:12 UTC

**Comment by bgilmer77** [comment] 2017-09-03 22:20
Looking at the Sitemap documentation for Colors, I do not read anything that would help me to understand the concept of a default color, or what the behavior or purpose of a default color would be.  I have not used colors much at all, so I cannot contribute something here, but certainly as an implementer of openHAB, if there is a default color, I would expect that fact to be discussed in the Colors section of the Sitemap documentation.

**Comment by ThomDietrich** [comment] 2017-09-03 23:28
In my understanding of the issue this was rather a misunderstanding and turned out to be a bug that was solved. There is no such thing as a default color because only special cases you select will receive special coloring. 
This should be settled. Is it?
