### ISSUE TITLE
IO/System Integration articles 404 from menu

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#330] opened 2017-02-17 12:32 UTC
@watou could you please have a look? http://docs.openhab.org/addons/io.html

**Comment by watou** [comment] 2017-02-17 13:39
Not sure what caused it, but I will submit a PR.

**Comment by watou** [comment] 2017-02-18 08:26
@ThomDietrich PR #332 submitted.

**Comment by kaikreuzer** [comment] 2017-02-20 07:48
@watou @ThomDietrich There is still a 404, if you navigate from the entries on http://docs.openhab.org/addons/io.html.

**Comment by watou** [comment] 2017-02-20 08:56
@kaikreuzer #332 only changed non-generated content and removed generated content that shouldn't have been added.  I was leaving the checking in of new generated content to you.  This would mean `git add addons/io`.  I can submit a PR with my generated content there, or you could on your next re-gen of the site.  What do you prefer I do now and in future PRs?

**Comment by watou** [comment] 2017-02-20 09:25
Added #338 so your normal "updated generated content" script ought to work after it's merged.

**Comment by kaikreuzer** [comment] 2017-02-20 09:51
Ah, sorry @watou, I must have missed that somehow - I had content regenerated locally, but I didn't correctly push it to giithub. Just updated everything now and the issue is indeed solved. Many thanks!

**Closed by kaikreuzer** 2017-02-20 09:51 UTC
